# Generated by Django 5.1.3 on 2025-01-17 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_column="code", db_index=True, max_length=20, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name", db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "description_text",
                    models.CharField(db_column="description_text", max_length=500),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="is_active", db_index=True, default=False
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Material",
                "verbose_name_plural": "Category Materials",
                "db_table": "dashboard.category_materials",
            },
        ),
        migrations.CreateModel(
            name="CuttingTechnique",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_column="code", db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name", db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "about_text",
                    models.CharField(db_column="about_text", max_length=500),
                ),
                (
                    "common_uses_text",
                    models.CharField(db_column="common_uses_text", max_length=500),
                ),
                (
                    "main_text",
                    models.CharField(db_column="main_text", max_length=500),
                ),
                (
                    "card_text",
                    models.CharField(db_column="card_text", max_length=250),
                ),
                (
                    "banner_image",
                    models.URLField(db_column="banner_image", max_length=2083),
                ),
                (
                    "main_image",
                    models.URLField(db_column="main_image", max_length=2083),
                ),
                (
                    "card_image",
                    models.URLField(db_column="card_image", max_length=2083),
                ),
                (
                    "about_image",
                    models.URLField(db_column="about_image", max_length=2083),
                ),
                (
                    "uses_image",
                    models.URLField(db_column="uses_image", max_length=2083),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="is_active", db_index=True, default=False
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutting Technique",
                "verbose_name_plural": "Cutting Techniques",
                "db_table": "dashboard.cutting_techniques",
                "permissions": [
                    (
                        "activate_cuttingtechnique",
                        "Can activate cutting technique",
                    ),
                    ("deactivate_cuttingtechnique", "Can deactivate cutting"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_column="code", db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name", db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "description_text",
                    models.CharField(db_column="description_text", max_length=500),
                ),
                (
                    "about_text",
                    models.CharField(db_column="about_text", max_length=500),
                ),
                (
                    "common_uses_text",
                    models.CharField(db_column="common_uses_text", max_length=500),
                ),
                (
                    "banner_image",
                    models.URLField(db_column="banner_image", max_length=2083),
                ),
                (
                    "description_image",
                    models.URLField(
                        db_column="description_image", max_length=2083
                    ),
                ),
                (
                    "about_image",
                    models.URLField(db_column="about_image", max_length=2083),
                ),
                (
                    "uses_image",
                    models.URLField(db_column="uses_image", max_length=2083),
                ),
                (
                    "texture_image",
                    models.URLField(db_column="texture_image", max_length=2083),
                ),
                (
                    "features_highlights",
                    models.JSONField(db_column="features_highlights"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="is_active", db_index=True, default=False
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.categorymaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "db_table": "dashboard.materials",
                "permissions": [
                    ("activate_material", "Can activate a material"),
                    ("deactivate_material", "Can deactivate a material"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ThicknessMaterial",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        db_column="value", decimal_places=2, max_digits=4
                    ),
                ),
                (
                    "compatibility_cut",
                    models.JSONField(db_column="compatibility_cut", default=dict),
                ),
                (
                    "material",
                    models.ForeignKey(
                        db_column="material",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thickness material",
                "verbose_name_plural": "Thicknesses materials",
                "db_table": "dashboard.thicknesses_materials",
            },
        ),
        migrations.CreateModel(
            name="UsesCuts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("number_uses", models.IntegerField(db_column="number_uses")),
                (
                    "cut",
                    models.OneToOneField(
                        db_column="cut",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.cuttingtechnique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Use cut",
                "verbose_name_plural": "Uses cuts",
                "db_table": "dashboard.uses_cuts",
            },
        ),
    ]
