# Generated by Django 5.1.3 on 2024-11-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="jwt",
            table="authentication.jwt",
        ),
        migrations.AlterModelTable(
            name="jwtblacklist",
            table="authentication.jwt_blacklist",
        ),
    ]
