# Generated by Django 5.1.3 on 2024-12-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_adminroledata"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users.users_uuid_262421_idx",
            old_name="users.user_uuid_5a965c_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users.users_email_2b80fd_idx",
            old_name="users.user_email_054a49_idx",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users.users",
        ),
    ]
