# Generated by Django 5.1.3 on 2025-02-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_adminrole_companyrole_naturalpersonrole_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users.users_uuid_262421_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users.users_email_2b80fd_idx",
        ),
    ]
